module_name: Block Contactinfos
compatible_versions: 1.0.0+
author: thirty bees
category: front office
tags:
  - cms pages
  - cms
  - cms links
short_description: The block contact infos allows you to enter contact information for your site's customer service.
description: description.md
images:
  - image-1.png
license: MIT